### ISSUE TITLE
No return for 'eid'.

### ISSUE THREAD

**Issue by raminsalmas** [dnanexus/UKB_RAP#13]
Hi, The command below doesn't work:

**df_qced['FID'] = df_qced['IID']**

I think there's a bug:

Bug:

 `fields = [fields_for_id(f)[0] for f in field_ids] + [participant.find_field(name='p20160_i0')]`

Debugged:

` fields = [fields_for_id(f)[0] for f in field_ids] + [participant.find_field(name='p20160_i0')] +  [participant.find_field(name='eid')]`

**Comment by anastazie-dnanexus** [comment]
Thank you for catching this. Feel free to make PR.

**Comment by mkoohim** [comment]
Thanks @raminsalmas for your help. I had the same issue and your comment helped me to solve it!

**Comment by ajlee21** [comment]
@raminsalmas would you mind submitting a PR with this change or pointing me to the notebook where you found this bug so that I can update it please.

**Comment by ajlee21** [comment]
Fixed in https://github.com/dnanexus/UKB_RAP/pull/39
