### ISSUE TITLE
Json format for WDL workflow

### ISSUE THREAD

**Issue by dianacornejo** [dnanexus/UKB_RAP#24]
Hi @anastazie-dnanexus 

Thanks for all the tutorials on UKB-RAP use

I'm very new to WDL and I was wondering how would the json file look for this specific example of the geno_bgen_files/geno_sample_files. Is this a text file that contains the name of one bgen file per line? Can you provide an example of this within the DNAnexus file system? 

```
workflow bgens_qc {
  input {
    Array[File]+ geno_bgen_files
    Array[File]+ geno_sample_files
    Boolean ref_first = true
    File? keep_file
    Array[File] extract_files
    String plink2_options = ""
    String output_prefix
  }
```

Thanks a lot

**Comment by anastazie-dnanexus** [comment]
Thank you for your comment. I moved WDL to [folder](https://github.com/dnanexus/UKB_RAP/tree/main/end_to_end_gwas_phewas/bgens_qc) and added JupyterNotebook to generate JSON file with input files. More details in [README](https://github.com/dnanexus/UKB_RAP/blob/main/end_to_end_gwas_phewas/bgens_qc/README.md).
