### ISSUE TITLE
Query exceeded timeout [120]

### ISSUE THREAD

**Issue by M-xiao815** [dnanexus/UKB_RAP#29]
command:
cohort_template <- "dx extract_dataset {dataset} --fields {field_list} -o cohort_data.csv"
cmd <- glue::glue(cohort_template)
system(cmd)

bug:
{'type': 'QueryTimeOut', 'message': 'Query exceeded timeout [120]. Cancelled', 'details': {}, 'time': '05/30/2023, 08:08:18'}

**Comment by Arkarachai** [comment]
Thanks for reporting. This is a known issue. By design, the large number of field extraction should be done in spark.

**Comment by anastazie-dnanexus** [comment]
Check [documentation](https://documentation.dnanexus.com/user/jupyter-notebooks/dxjupyterlab-spark-cluster/exploring-and-querying-with-spark)dx extract_dataset to generate SQL query.
