### ISSUE TITLE
No need to liftover to Hg38

### ISSUE THREAD

**Issue by nshrine** [dnanexus/UKB_RAP#31]
On this page:
https://github.com/dnanexus/UKB_RAP/tree/main/end_to_end_gwas_phewas/liftover_plink_beds_tmp
It says:
"In order to perform association testing with the sequncing data on step-2, it is required to get the array genotyping data on the same reference coordinate as the sequencing data."

Whereas it seems it is actually not required but simply desirable:
https://github.com/rgcgithub/regenie/issues/82

**Comment by Arkarachai** [comment]
Yes, I confirm this is correct based on discussion with Regenie developer. Mainly we try to avoid translocation among different version. However, we will clarify this to avoid confusion. 
@oklempir-cf

**Comment by anastazie-dnanexus** [comment]
Thank you for catching this, I edited README by saying that it is desirable and added link to regenies discussion.
