### ISSUE TITLE
Running function "main" of "regenie_test_associations" failed because of AppInternalError

### ISSUE THREAD

**Issue by WeiChenPan** [dnanexus/UKB_RAP#34]
Hi, everyone
This is our first time to use UKB_RAP.
We're running regenie for GWAS, the step 1 process was successful, but we encountered some problem during step 2 (below is the log file).
Is there anyone having the same problem?

Options in effect:
--step 2 \
--bgen ukb00000_c21_b0_v1.bgen \
--phenoFile Hematologic_malignancy_imputation.phe \
--bsize 200 \
--pThresh 0.05 \
--test additive \
--pred ukb_c1-22_GRCh38_full_analysis_set_plus_decoy_hla_merged_pred.list \
--gz \
--sample ukb00000_c21_b0_v1.sample \
--extract /home/dnanexus/gel_imputed_snps_data_qc_pass_HM.snplist \
--covarFile Hematologic_malignancy_imputation.phe \
--bt \
--spa \
--phenoColList Hematologic_malignancy_cc \
--covarColList sex,age,ethnic_background,alcohol_status,hypertension,ever_smoked,SBP,BMI,NLR,CRP \
--ref-first \
--htp ukb00000_c21_b0_v1 \
--out ukb00000_c21_b0_v1
Association testing mode with fast multithreading using OpenMP
* bgen : [ukb00000_c21_b0_v1.bgen]
-summary : bgen file (v1.2 layout, zstd compressed) with 488315 anonymous samples and 4376829 variants with 8-bit encoding.
-index bgi file [ukb00000_c21_b0_v1.bgen.bgi]
ERROR: BGenError
Traceback (most recent call last):
  File "/home/dnanexus/job-GfKBQ7QJ3ZvYYY5Y9z3QffzY", line 39, in <module>
    exec_code(job_code, _code_filename)
  File "/home/dnanexus/job-GfKBQ7QJ3ZvYYY5Y9z3QffzY", line 25, in exec_code
    exec(compiled_code, globals())
  File "/home/dnanexus/job-GfKBQ7QJ3ZvYYY5Y9z3QffzY.code.py", line 208, in <module>
    dxpy.run()
  File "/usr/local/lib/python3.8/dist-packages/dxpy/utils/exec_utils.py", line 150, in run
    result = ENTRY_POINT_TABLE[job['function']](**job['input'])
  File "/home/dnanexus/job-GfKBQ7QJ3ZvYYY5Y9z3QffzY.code.py", line 103, in main
    docker.run(cmd)
  File "/usr/lib/python3/dist-packages/sugar/dockertools.py", line 347, in run
    self._handle_last_process_cpe(cpe)
  File "/usr/lib/python3/dist-packages/sugar/dockertools.py", line 368, in _handle_last_process_cpe
    raise cpe
  File "/usr/lib/python3/dist-packages/sugar/dockertools.py", line 337, in run
    self._last_process = processing.run(
  File "/usr/lib/python3/dist-packages/sugar/processing/__init__.py", line 122, in run
    processes.block()
  File "/usr/lib/python3/dist-packages/sugar/processing/core.py", line 462, in block
    self.raise_if_error()
  File "/usr/lib/python3/dist-packages/sugar/processing/core.py", line 576, in raise_if_error
    raise CalledProcessError(self.returncode, str(self), output=msg)
subprocess.CalledProcessError: Command 'docker run -e PYTHONUNBUFFERED=s -v /home/dnanexus:/home/dnanexus -w /home/dnanexus --rm dnanexus/regenie:latest bash -c 'regenie --step 2 --bgen ukb00000_c21_b0_v1.bgen --phenoFile Hematologic_malignancy_imputation.phe --bsize 200 --pThresh 0.05 --test additive --pred ukb_c1-22_GRCh38_full_analysis_set_plus_decoy_hla_merged_pred.list --gz --sample ukb00000_c21_b0_v1.sample --extract /home/dnanexus/gel_imputed_snps_data_qc_pass_HM.snplist --covarFile Hematologic_malignancy_imputation.phe --bt --spa --phenoColList Hematologic_malignancy_cc --covarColList sex,age,ethnic_background,alcohol_status,hypertension,ever_smoked,SBP,BMI,NLR,CRP --ref-first --htp ukb00000_c21_b0_v1 --out ukb00000_c21_b0_v1'' returned non-zero exit status 1.
Close

**Comment by anastazie-dnanexus** [comment]
Hello, @WeiChenPan is there any specific reason why you were running REGENIE steps separatelyand not as one step using [DNAnexus regenie app](https://ukbiobank.dnanexus.com/app/regenie)? I am assuming that you are using REGENIE app [Step 1](https://ukbiobank.dnanexus.com/app/regenie_fit_wgr) and [Step 2](https://ukbiobank.dnanexus.com/app/regenie_test_associations) or you were running REGENIE in Swiss Army Knife or cloudworkstation/ttyd/Jupyterlab?

**Comment by oklempir-cf** [comment]
Another idea - I am seeing that the error message "ERROR: BGenError" appeared just after it printed out the line **-index bgi file [ukb00000_c21_b0_v1.bgen.bgi]**. If I am not mistaken, I am not seeing bgen index file as an input to step 2. Could this fact be that reason for job failure?

**Comment by WeiChenPan** [comment]
@anastazie-dnanexus 
@oklempir-cf 
We've already solved the problem. The error is because the current .bgi index files for GEL BGEN data were created using a different version of the BGEN files, therefore, it caused the error while reading. 
So, the resolution is to create new .bgi files by using the swiss-army-knife app through the RAP.
